name: Build and Publish
on:
  push:
    branches:
      - master
      - 'release-*'
      - TRELLO-120
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:


jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Avni Server Repository
        uses: actions/checkout@v3
        with:
          path: avni-server
      
      - name: Checkout Avni WebApp Repository
        uses: actions/checkout@v3
        with:
          repository: avniproject/avni-webapp
          path: avni-webapp

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Build and Package Avni Server
        run:
          cd avni-server && ./gradlew clean build -x test
      - name: Build and Package Avni Webapp
        run:
          cd avni-webapp && yarn install --frozen-lockfile && yarn build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: avni-server/package/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bahmni/avni-server:latest
