name: Build and Publish
on:
  push:
    branches:
      - master
      - 'release-*'
      - TRELLO-120
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:


jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Avni Server Repository
        uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Build and Package Avni Server
        run: ./gradlew clean build -x test
      - name: Download and extract Avni Webapp
        run: |
          mkdir avni-webapp-build
          curl -L -o avni-webapp.zip https://output.circle-artifacts.com/output/job/10acc1ad-94b7-4669-bb92-99a414503789/artifacts/0/~/artifacts/openchs-webapp.zip
          unzip -d avni-webapp-build avni-webapp.zip
          rm -rf avni-webapp.zip
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bahmnihwc/avni-server:latest
