name: Build and Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-avni-webapp:
    name: Build Avni Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Avni Web App Repository
        uses: actions/checkout@v3
        with:
          repository: avniproject/avni-webapp
          ref: master
      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Build admin app
        run: yarn run react-scripts --openssl-legacy-provider --max_old_space_size=4096 build
      - uses: actions/upload-artifact@v3
        name: Upload build artifact
        with:
          name: avni-webapp-build
          path: build/

  build-publish-docker:
    name: Build & Publish Docker Image
    needs: [build-avni-webapp]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Avni Server Repository
        uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "8"
      - name: Build and Package Avni Server
        run: ./gradlew clean build -x test
      - uses: actions/download-artifact@v3
        with:
          name: avni-webapp-build
          path: avni-webapp-build/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bahmnihwc/avni-server:master-${{ github.run_number }},bahmnihwc/avni-server:latest
